pipeline:
  name: Demo App Deploy
  identifier: demo_app_deploy
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy to Dev
        identifier: deploy_dev
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: demo_app
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev_k8s
          execution:
            steps:
              - step:
                  type: K8sApply
                  name: Deploy
                  identifier: deploy
                  spec:
                    filePaths:
                      - manifests
                    skipDryRun: false
                    skipSteadyStateCheck: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  type: K8sRollback
                  name: Rollback
                  identifier: rollback
                  spec: {}
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
